### ISSUE TITLE
[Optional] Enhanced Battle Mechanism

### ISSUE THREAD

**Issue by wxiang54** [joel99/Team_2D#1]
<b><h4>Risk's troop battle mechanism is too random for our liking.</h4></b>

Have different types of troops: Certain have advantages, weaknesses, over others. 
Engage mini battle - similar die rolling, except troops might have ranks, and HP.
(level up through battles taken)
(everyone starts with one general)
More details TBA.

**Comment by joel99** [comment]
Not enough time for this mechanism.
