### ISSUE TITLE
Game update(Country c) not working properly

### ISSUE THREAD

**Issue by joel99** [joel99/Team_2D#6]
When conquering, as numbers reach into 2 digits and later get overwritten into a one digit number, residue remains (14 -> 8 looks like 14 -> 48). Fix the update() function in Game.java to avoid this.

**Comment by joel99** [comment]
bump, this is fairly important

**Comment by wxiang54** [comment]
Original:
'''java
while (Util.userChars.indexOf(map.get(x++,y)) != -1)
		map.set(x,y, ' ');
'''

The x++ was testing if the space was a non-alphanumeric, but if it was, the char *to the right* of it would be changed. 

Just changed x++ to x and all was fixed :smile:
