### ISSUE TITLE
Skipping Reinforcement

### ISSUE THREAD

**Issue by wxiang54** [joel99/Team_2D#7]
When playing with 2 (and only 2) players, the game skips both initial and turn-based reinforcement for both players. This may have something to do with the new system where we can have < 6 players. See if you can diagnose the problem and fix this in Risk.java.

Example:
![2-player bug](https://i.gyazo.com/3259b3b32d4e4e735e4d976b4af0180d.png)

**Comment by joel99** [comment]
Ezpzlmnsqz
